### ISSUE TITLE
Python 3.8.0 warning on bad equality check

### ISSUE THREAD

**Issue by mmesbah** [s3tools/s3cmd#1055]
The warning is simple.

```
/usr/local/bin/s3cmd:308: SyntaxWarning: "is" with a literal. Did you mean "=="?
      if response["status"] is 200:
/usr/local/bin/s3cmd:310: SyntaxWarning: "is" with a literal. Did you mean "=="?
      elif response["status"] is 204:
```

Simple replace "is" with "==" on mentioned locations.

**Comment by fviard** [comment]
thanks for the report!

**Comment by jamieburchell** [comment]
When might we see a release that incorporates this fix? My logs are full of this.

**Comment by mschindl** [comment]
The issue still exists when s3cmd is installed with brew, because of the usage by python 3.8.1.
Python 2.7.x crates not following warnung.

% ls /usr/local/Cellar/s3cmd/2.0.2_2/libexec
.Python -> ../../../python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/Python

% s3cmd --version
s3cmd version 2.0.2

% s3cmd ls
/usr/local/bin/s3cmd:308: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if response["status"] is 200:
/usr/local/bin/s3cmd:310: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif response["status"] is 204:

[object storage bucket list]

**Comment by tkensiski** [comment]
This is also an issue with python 3.6.8

**Comment by kode54** [comment]
The fix was pushed to a release 3 days ago. Now is the time to go bug Homebrew to look at Github for releases instead of SourceForge.

**Comment by fviard** [comment]
Fyi, new releases are published in sync on Sourceforge and Github.

**Comment by neilclypd** [comment]
s3cmd 2.1.0 is now available via brew, see https://github.com/Homebrew/homebrew-core/pull/52727

**Comment by fviard** [comment]
@neilclypd Thank you very much.
If ever you would like to follow the future releases to also update them in Homebrew, you can subscribe to the following mailing list:
s3tools-announce@lists.sourceforge.net 
There is almost no traffic on it, just a message once in a while to notify new releases.

**Comment by laurenz-glueck** [comment]
I have s3cmd 2.1.0 installed (via homebrew) but still getting the SyntaxWarning:
`/usr/local/Cellar/s3cmd/2.1.0/libexec/lib/python3.8/site-packages/magic.py:193: SyntaxWarning: "is" with a literal. Did you mean "=="?`

**Comment by fviard** [comment]
@laurenz-glueck This time it is an issue not with s3cmd but with one of its dependency.
Please have a look at #1107

**Comment by nailarch** [comment]
The same issue on Ubuntu 20.04:
/usr/bin/s3cmd:308: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if response["status"] is 200:
/usr/bin/s3cmd:310: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif response["status"] is 204:

**Comment by nailarch** [comment]
https://bugs.launchpad.net/ubuntu/+source/s3cmd/+bug/1874651
