### ISSUE TITLE
--signature-v2 doesn't seem to be kept in recursive mode - Scality bug

### ISSUE THREAD

**Issue by dwyart** [s3tools/s3cmd#477]
It seems that recursive mode is not handling --signature-v2 correctly : at top level, the option is applied, but when going down one level, it seems to be lost, and we get errors.

doing a "rb -f --recursive" fails because of this.

Thanks

**Comment by mdomsch** [comment]
What version please?  This may have been fixed in 1.5.0 with commit
86ebf0118d53acc81cf8f7070f41cccfa4c20a7b.  With current HEAD, it seems to
work for me as expected.  Please post further debug information if you are
having problems with 1.5.2 or current HEAD.

**Comment by dwyart** [comment]
Yes this is with current HEAD.

Here is a sample session:

```
$ ~/s3cmd/s3cmd --signature-v2 mb s3://damien
Bucket 's3://damien/' created
$ ~/s3cmd/s3cmd --signature-v2 put /etc/hosts s3://damien
/etc/hosts -> s3://damien/hosts  [1 of 1]
 193 of 193   100% in    0s     2.10 kB/s  done
$ ~/s3cmd/s3cmd --signature-v2 put /etc/inittab s3://damien
/etc/inittab -> s3://damien/inittab  [1 of 1]
 2018 of 2018   100% in    0s    26.40 kB/s  done
$ ~/s3cmd/s3cmd --signature-v2 rb -f --recursive s3://damien
WARNING: Bucket is not empty. Removing all the objects from it first. This may take some time...
ERROR: S3 error:
$ ~/s3cmd/s3cmd --signature-v2 ls s3://damien
2015-02-09 14:31       193   s3://damien/hosts
2015-02-09 14:31      2018   s3://damien/inittab
$ ~/s3cmd/s3cmd --signature-v2 rm s3://damien/hosts
File s3://damien/hosts deleted
$ ~/s3cmd/s3cmd --signature-v2 rm s3://damien/inittab
File s3://damien/inittab deleted
$ ~/s3cmd/s3cmd --signature-v2 rb s3://damien
Bucket 's3://damien/' removed
```
Note this is not tested against a pristine Amazon S3 server but a compatible implementation (bot supporting the latest signature standard). The same test with a very old 0.9.9 works (at the recursive step).

Here is a more detailed output:

```
$ ~/s3cmd/s3cmd -v -d --signature-v2 rb -f --recursive s3://damien
DEBUG: ConfigParser: Reading file '/home/dw/.s3cfg'                                                                                                                           DEBUG: ConfigParser: host_base->demo.scality.com
DEBUG: ConfigParser: host_bucket->%(bucket)s.demo.scality.com
DEBUG: ConfigParser: secret_key->CS...7_chars...s
DEBUG: ConfigParser: access_key->sc...6_chars...s
DEBUG: Updating Config.Config cache_file ->
DEBUG: Updating Config.Config follow_symlinks -> False
DEBUG: Updating Config.Config force -> True
DEBUG: Updating Config.Config recursive -> True
DEBUG: Updating Config.Config signature_v2 -> True
DEBUG: Updating Config.Config verbosity -> 10
DEBUG: Unicodising 'rb' using ISO-8859-1
DEBUG: Unicodising 's3://damien' using ISO-8859-1
DEBUG: Command: rb
DEBUG: CreateRequest: resource[uri]=/
DEBUG: Using signature v2
DEBUG: SignHeaders: 'DELETE\n\n\n\nx-amz-date:Mon, 09 Feb 2015 14:39:01 +0000\n/damien/'
DEBUG: Processing request, please wait...
DEBUG: get_hostname(damien): damien.demo.scality.com
DEBUG: ConnMan.get(): creating new connection: http://damien.demo.scality.com
DEBUG: non-proxied HTTPConnection(damien.demo.scality.com)
DEBUG: format_uri(): /
DEBUG: Sending request method_string='DELETE', uri='/', headers={'Authorization': 'AWS scalitycs:1h2A/oahdeAiMuPmxEg9JmDlAB4=', 'x-amz-date': 'Mon, 09 Feb 2015 14:39:01 +0000'}, body=(0 bytes)
DEBUG: Response: {'status': 409, 'headers': {'content-length': '135', 'server': 'RestServer/1.0', 'connection': 'keep-alive', 'cache-control': 'no-cache', 'date': 'Mon, 09 Feb 2015 14:39:06 GMT', 'content-type': 'application/xml'}, 'reason': 'Conflict', 'data': '<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>BucketNotEmpty</Code>\n<Message></Message>\n<BucketName>damien</BucketName>\n</Error>\n'}
DEBUG: ConnMan.put(): connection put back to pool (http://damien.demo.scality.com#1)
DEBUG: S3Error: 409 (Conflict)
DEBUG: HttpHeader: content-length: 135
DEBUG: HttpHeader: server: RestServer/1.0
DEBUG: HttpHeader: connection: keep-alive
DEBUG: HttpHeader: cache-control: no-cache
DEBUG: HttpHeader: date: Mon, 09 Feb 2015 14:39:06 GMT
DEBUG: HttpHeader: content-type: application/xml
DEBUG: ErrorXML: Code: 'BucketNotEmpty'
DEBUG: ErrorXML: Message: None
DEBUG: ErrorXML: BucketName: 'damien'
WARNING: Bucket is not empty. Removing all the objects from it first. This may take some time...
INFO: Retrieving list of remote files for s3://damien/ ...
DEBUG: CreateRequest: resource[uri]=/
DEBUG: Using signature v2
DEBUG: SignHeaders: 'GET\n\n\n\nx-amz-date:Mon, 09 Feb 2015 14:39:06 +0000\n/damien/'
DEBUG: Processing request, please wait...
DEBUG: get_hostname(damien): damien.demo.scality.com
DEBUG: ConnMan.get(): re-using connection: http://damien.demo.scality.com#1
DEBUG: format_uri(): /
DEBUG: Sending request method_string='GET', uri='/', headers={'Authorization': 'AWS scalitycs:E6uPlykTH5ydBt1fNTx+AOMUBrI=', 'x-amz-date': 'Mon, 09 Feb 2015 14:39:06 +0000'}, body=(0 bytes)
DEBUG: Response: {'status': 200, 'headers': {'content-length': '865', 'server': 'RestServer/1.0', 'connection': 'keep-alive', 'cache-control': 'no-cache', 'date': 'Mon, 09 Feb 2015 14:39:06 GMT', 'content-type': 'application/xml'}, 'reason': 'OK', 'data': '<?xml version="1.0" encoding="UTF-8"?>\n<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>damien</Name><Prefix></Prefix><Marker></Marker><MaxKeys>1000</MaxKeys><IsTruncated>false</IsTruncated><Contents><Key>hosts</Key><LastModified>2015-02-09T14:38:54.000Z</LastModified><ETag>&quot;e8e0b85479e3c9d51e0a2d9549ea9000&quot;</ETag><Size>193</Size><Owner><ID>55C0F2E0392A511055C0F2000000004000000120</ID><DisplayName>Scality Customer Service</DisplayName></Owner><StorageClass>STANDARD</StorageClass></Contents><Contents><Key>inittab</Key><LastModified>2015-02-09T14:38:54.000Z</LastModified><ETag>&quot;0ebfc6ed8d3299b10c86f1bde848a180&quot;</ETag><Size>2018</Size><Owner><ID>55C0F2E0392A511055C0F2000000004000000120</ID><DisplayName>Scality Customer Service</DisplayName></Owner><StorageClass>STANDARD</StorageClass></Contents></ListBucketResult>'}
DEBUG: ConnMan.put(): connection put back to pool (http://damien.demo.scality.com#2)
DEBUG: Applying --exclude/--include
DEBUG: CHECK: hosts
DEBUG: PASS: 'hosts'
DEBUG: CHECK: inittab
DEBUG: PASS: 'inittab'
DEBUG: Batch delete 2, remaining 0
DEBUG: CreateRequest: resource[uri]=/?delete
DEBUG: Using signature v2
DEBUG: SignHeaders: 'POST\ncN9ycehxeVXbUVP80hK9Rw==\napplication/xml\n\nx-amz-date:Mon, 09 Feb 2015 14:39:06 +0000\n/damien/?delete'
DEBUG: Processing request, please wait...
DEBUG: get_hostname(damien): damien.demo.scality.com
DEBUG: ConnMan.get(): re-using connection: http://damien.demo.scality.com#2
DEBUG: format_uri(): /?delete
DEBUG: Sending request method_string='POST', uri='/?delete', headers={'content-type': 'application/xml', 'Authorization': 'AWS scalitycs:lnelYsbNPx0xoMtsQtVTVVy/Q3g=', 'x-amz-date': 'Mon, 09 Feb 2015 14:39:06 +0000', 'content-md5': 'cN9ycehxeVXbUVP80hK9Rw=='}, body=(123 bytes)
DEBUG: Response: {'status': 403, 'headers': {'content-length': '110', 'server': 'RestServer/1.0', 'connection': 'close', 'cache-control': 'no-cache', 'date': 'Mon, 09 Feb 2015 14:39:06 GMT', 'content-type': 'application/xml'}, 'reason': 'Forbidden', 'data': '<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SignatureDoesNotMatch</Code>\n<Message></Message>\n</Error>\n'}
DEBUG: ConnMan.put(): connection put back to pool (http://damien.demo.scality.com#3)
ERROR: S3 error:
```

Thanks

**Comment by mdomsch** [comment]
It's using signature v2 the whole time, as expected, but it's getting a 'signature does not match' error from your scality server when issuing the batch delete command.  The same signing routine succeeded in all the previous calls.  Any chance we can get the debug logs from that scality server?  It's not one I've seen before of have an instance of.

**Comment by dwyart** [comment]
Here are some traces.

First, with HEAD:

```
==> authbws-201502160000-0.log <==

20150216 11:45:12.924 MOD_MSGSTORE_AUTH_BWS authbws_xmlrpc_req: reply user="scalitycs" id="scalitycs" dname="Scality Customer Service" pkey="<hidden>" flags="0" bucketmaxnr="100" bucketmaxsize="-1" reqmaxnr="-1"


==> chordbucket-201502160000-0.log <==

20150216 11:45:12.924 chordbucket id=0x1324ac00 action=GET_BUCKETACL bucketid=E212260000000000000000321592594000000220

20150216 11:45:12.924 chordbucket id=0x1324ac00 action=GET_BUCKETACL status=SUCCESS

20150216 11:45:12.924 chordbucket id=0xc4b57d0 action=GET_BUCKETACL bucketid=E212260000000000000000321592594000000220

20150216 11:45:12.924 chordbucket id=0xc4b57d0 action=GET_BUCKETACL status=SUCCESS

20150216 11:45:12.924 chordbucket id=0xc420290 action=DEL_BUCKET userid=55C0F2E0392A511055C0F2000000004000000120 bucketid=E212260000000000000000321592594000000220 bucketname=bmor

20150216 11:45:12.924 chordbucket id=0xc420290 action=DEL_BUCKET status=FAILURE_BUCKETNOTEMPTY

20150216 11:45:12.924 chordbucket id=0x1328ebd0 action=GET_BUCKETACL bucketid=E212260000000000000000321592594000000220

20150216 11:45:12.924 chordbucket id=0x1328ebd0 action=GET_BUCKETACL status=SUCCESS

20150216 11:45:12.924 chordbucket id=0xc46f8f0 action=GET_BUCKETACL bucketid=E212260000000000000000321592594000000220

20150216 11:45:12.924 chordbucket id=0xc46f8f0 action=GET_BUCKETACL status=SUCCESS

20150216 11:45:12.924 chordbucket id=0xc424fb0 action=GET_BUCKET bucketid=E212260000000000000000321592594000000220

20150216 11:45:12.924 chordbucket id=0xc424fb0 action=GET_BUCKET status=SUCCESS


==> restapi-201502160000-0.log <==

20150216 11:45:12.924 restapi id=0xd056c10 context="generic" cmd="postreadreq" src="94.23.237.168" step="REQ_START" method="DELETE" uri="/menu"

20150216 11:45:12.924 restapi id=0xd056c10 context="bws" cmd="parseauthz_header" status="ok" login="scalitycs" signature="DEkv5eaNTuJpqXMtGgiw6YYiBis="

20150216 11:45:12.924 restapi id=0xd056c10 context="bws" cmd="auth" status="200" user="scalitycs" userid="scalitycs" displayname="Scality Customer Service"

20150216 11:45:12.924 restapi id=0xd056c10 context="bws" src="94.23.237.168" action="BWS_DELETE_BUCKET" bucketid="E212260000000000000000321592594000000220" bucketname="bmor" userid="55C0F2E0392A511055C0F2000000004000000120" username="scalitycs" step="REQ_START"

20150216 11:45:12.924 restapi id=0xd056c10 context="bws" cmd="content_handler" status="ok"

20150216 11:45:12.924 restapi id=0xd056c10 context="generic" cmd="seterror" msg="BucketNotEmpty" code="409"

20150216 11:45:12.924 restapi id=0xd056c10 context="bws" src="94.23.237.168" action="BWS_DELETE_BUCKET" bucketid="E212260000000000000000321592594000000220" bucketname="bmor" userid="55C0F2E0392A511055C0F2000000004000000120" username="scalitycs" step="REQ_END" status="409"

20150216 11:45:12.924 restapi id=0xd056c10 context="generic" cmd="finished" src="94.23.237.168" step="REQ_END" method="DELETE" uri="/" code="409" elapsed="16ms" input_size="0bytes" output_size="133bytes"

20150216 11:45:12.924 restapi id=0x10a29650 context="generic" cmd="postreadreq" src="94.23.237.168" step="REQ_START" method="GET" uri="/menu"

20150216 11:45:12.924 restapi id=0x10a29650 context="bws" cmd="parseauthz_header" status="ok" login="scalitycs" signature="9o3mWXMdpy/pu17o9z98yDZSPtU="

20150216 11:45:12.924 restapi id=0x10a29650 context="bws" cmd="auth" status="200" user="scalitycs" userid="scalitycs" displayname="Scality Customer Service"

20150216 11:45:12.924 restapi id=0x10a29650 context="bws" src="94.23.237.168" action="BWS_GET_BUCKET" bucketid="E212260000000000000000321592594000000220" bucketname="bmor" userid="55C0F2E0392A511055C0F2000000004000000120" username="scalitycs" step="REQ_START"

20150216 11:45:12.924 restapi id=0x10a29650 context="bws" cmd="content_handler" status="ok"

20150216 11:45:12.924 restapi id=0x10a29650 context="bws" cmd="listbucket" name="bmor" prefix="" marker="" next="hosts" max_keys="1000" delimiter="" is_truncated="false"

20150216 11:45:12.924 restapi id=0x10a29650 context="bws" src="94.23.237.168" action="BWS_GET_BUCKET" bucketid="E212260000000000000000321592594000000220" bucketname="bmor" userid="55C0F2E0392A511055C0F2000000004000000120" username="scalitycs" step="REQ_END" status="200" nrobjects="1"

20150216 11:45:12.924 restapi id=0x10a29650 context="generic" cmd="finished" src="94.23.237.168" step="REQ_END" method="GET" uri="/" code="200" elapsed="7ms" input_size="0bytes" output_size="545bytes"

20150216 11:45:12.924 restapi id=0xd056c10 context="generic" cmd="postreadreq" src="94.23.237.168" step="REQ_START" method="POST" uri="/?delete"

20150216 11:45:12.924 restapi id=0xd056c10 context="bws" cmd="parseauthz_header" status="ok" login="scalitycs" signature="YWK93k58vf5bHSBvPVhWKiPDvNo="

20150216 11:45:12.924 restapi id=0xd056c10 context="generic" cmd="seterror" msg="SignatureDoesNotMatch" code="403"

20150216 11:45:12.924 restapi id=0xd056c10 context="bws" cmd="auth" status="403" user="scalitycs" userid="(empty)" displayname="(empty)"

20150216 11:45:12.924 restapi id=0xd056c10 context="bws" src="94.23.237.168" action="BWS_GET_LISTALLMYBUCKETS" step="REQ_END" status="error" code="403" reason="SignatureDoesNotMatch"

20150216 11:45:12.924 restapi id=0xd056c10 context="generic" cmd="postreadreq" src="94.23.237.168" step="REQ_ERR" method="POST" uri="/?delete" status="error" code="403" elapsed="0ms"

20150216 11:45:12.924 restapi id=0xd056c10 context="generic" cmd="finished" src="94.23.237.168" step="REQ_END" method="POST" uri="/?delete" code="403" elapsed="0ms" input_size="0bytes" output_size="110bytes"
```

And with 0.9.9:
```


==> authbws-201502160000-0.log <==

20150216 11:50:13.702 MOD_MSGSTORE_AUTH_BWS authbws_xmlrpc_req: reply user="scalitycs" id="scalitycs" dname="Scality Customer Service" pkey="<hidden>" flags="0" bucketmaxnr="100" bucketmaxsize="-1" reqmaxnr="-1"


==> chordbucket-201502160000-0.log <==

20150216 11:50:13.702 chordbucket id=0x10a1a310 action=GET_BUCKETACL bucketid=E212260000000000000000321592594000000220

20150216 11:50:13.702 chordbucket id=0x10a1a310 action=GET_BUCKETACL status=SUCCESS

20150216 11:50:13.702 chordbucket id=0x13272f00 action=GET_BUCKETACL bucketid=E212260000000000000000321592594000000220

20150216 11:50:13.702 chordbucket id=0x13272f00 action=GET_BUCKETACL status=SUCCESS

20150216 11:50:13.702 chordbucket id=0xc4b57d0 action=DEL_BUCKET userid=55C0F2E0392A511055C0F2000000004000000120 bucketid=E212260000000000000000321592594000000220 bucketname=bmor

20150216 11:50:13.702 chordbucket id=0xc4b57d0 action=DEL_BUCKET status=FAILURE_BUCKETNOTEMPTY

20150216 11:50:13.702 chordbucket id=0xc3dafd0 action=GET_BUCKETACL bucketid=E212260000000000000000321592594000000220

20150216 11:50:13.702 chordbucket id=0xc3dafd0 action=GET_BUCKETACL status=SUCCESS

20150216 11:50:13.702 chordbucket id=0x1328ebd0 action=GET_BUCKETACL bucketid=E212260000000000000000321592594000000220

20150216 11:50:13.702 chordbucket id=0x1328ebd0 action=GET_BUCKETACL status=SUCCESS

20150216 11:50:13.702 chordbucket id=0xc420290 action=GET_BUCKET bucketid=E212260000000000000000321592594000000220

20150216 11:50:13.702 chordbucket id=0xc420290 action=GET_BUCKET status=SUCCESS

20150216 11:50:13.702 chordbucket id=0xc46f8f0 action=GET_BUCKETACL bucketid=E212260000000000000000321592594000000220

20150216 11:50:13.702 chordbucket id=0xc46f8f0 action=GET_BUCKETACL status=SUCCESS

20150216 11:50:13.702 chordbucket id=0xef67080 action=GET_BUCKETACL bucketid=E212260000000000000000321592594000000220

20150216 11:50:13.702 chordbucket id=0xef67080 action=GET_BUCKETACL status=SUCCESS

20150216 11:50:13.702 chordbucket id=0xc424fb0 action=DEL_OBJ bucketid=E212260000000000000000321592594000000220 objid=ACDDA3691EA7426D4ECF85321592594000000320 objname=hosts

20150216 11:50:13.702 chordbucket id=0xc424fb0 action=UPDATE_BUCKET bucketid=E212260000000000000000321592594000000220 actiontype=DEL objname=hosts

20150216 11:50:13.702 chordbucket id=0xc424fb0 action=UPDATE_BUCKET status=SUCCESS elapsed=38ms retries=0

20150216 11:50:13.702 chordbucket id=0xc424fb0 action=DEL_OBJ status=SUCCESS

20150216 11:50:13.702 chordbucket id=0xeddb950 action=GET_BUCKETACL bucketid=E212260000000000000000321592594000000220

20150216 11:50:13.702 chordbucket id=0xeddb950 action=GET_BUCKETACL status=SUCCESS

20150216 11:50:13.702 chordbucket id=0xee7dd20 action=GET_BUCKETACL bucketid=E212260000000000000000321592594000000220

20150216 11:50:13.702 chordbucket id=0xee7dd20 action=GET_BUCKETACL status=SUCCESS

20150216 11:50:13.702 chordbucket id=0x132a2a50 action=DEL_BUCKET userid=55C0F2E0392A511055C0F2000000004000000120 bucketid=E212260000000000000000321592594000000220 bucketname=bmor

20150216 11:50:13.702 chordbucket id=0x132a2a50 action=UPDATE_BUCKET bucketid=55C0F2E0392A511055C0F2000000004000000120 actiontype=DEL objname=bmor

20150216 11:50:13.702 chordbucket id=0x132a2a50 action=UPDATE_BUCKET status=SUCCESS elapsed=43ms retries=0

20150216 11:50:13.702 chordbucket id=0x132a2a50 action=DEL_BUCKET status=SUCCESS


==> restapi-201502160000-0.log <==

20150216 11:50:13.702 restapi id=0xc432850 context="generic" cmd="postreadreq" src="94.23.237.168" step="REQ_START" method="DELETE" uri="/menu"

20150216 11:50:13.702 restapi id=0xc432850 context="bws" cmd="parseauthz_header" status="ok" login="scalitycs" signature="8TwhPzvkcnXVCgzTgW7/P/cMHLU="

20150216 11:50:13.702 restapi id=0xc432850 context="bws" cmd="auth" status="200" user="scalitycs" userid="scalitycs" displayname="Scality Customer Service"

20150216 11:50:13.702 restapi id=0xc432850 context="bws" src="94.23.237.168" action="BWS_DELETE_BUCKET" bucketid="E212260000000000000000321592594000000220" bucketname="bmor" userid="55C0F2E0392A511055C0F2000000004000000120" username="scalitycs" step="REQ_START"

20150216 11:50:13.702 restapi id=0xc432850 context="bws" cmd="content_handler" status="ok"

20150216 11:50:13.702 restapi id=0xc432850 context="generic" cmd="seterror" msg="BucketNotEmpty" code="409"

20150216 11:50:13.702 restapi id=0xc432850 context="bws" src="94.23.237.168" action="BWS_DELETE_BUCKET" bucketid="E212260000000000000000321592594000000220" bucketname="bmor" userid="55C0F2E0392A511055C0F2000000004000000120" username="scalitycs" step="REQ_END" status="409"

20150216 11:50:13.702 restapi id=0xc432850 context="generic" cmd="finished" src="94.23.237.168" step="REQ_END" method="DELETE" uri="/" code="409" elapsed="13ms" input_size="0bytes" output_size="133bytes"

20150216 11:50:13.702 restapi id=0xee97db0 context="generic" cmd="postreadreq" src="94.23.237.168" step="REQ_START" method="GET" uri="/menu"

20150216 11:50:13.702 restapi id=0xee97db0 context="bws" cmd="parseauthz_header" status="ok" login="scalitycs" signature="WHtdpxBF3R454P0YITXCWhDl4Y4="

20150216 11:50:13.702 restapi id=0xee97db0 context="bws" cmd="auth" status="200" user="scalitycs" userid="scalitycs" displayname="Scality Customer Service"

20150216 11:50:13.702 restapi id=0xee97db0 context="bws" src="94.23.237.168" action="BWS_GET_BUCKET" bucketid="E212260000000000000000321592594000000220" bucketname="bmor" userid="55C0F2E0392A511055C0F2000000004000000120" username="scalitycs" step="REQ_START"

20150216 11:50:13.702 restapi id=0xee97db0 context="bws" cmd="content_handler" status="ok"

20150216 11:50:13.702 restapi id=0xee97db0 context="bws" cmd="listbucket" name="bmor" prefix="" marker="" next="hosts" max_keys="1000" delimiter="" is_truncated="false"

20150216 11:50:13.702 restapi id=0xee97db0 context="bws" src="94.23.237.168" action="BWS_GET_BUCKET" bucketid="E212260000000000000000321592594000000220" bucketname="bmor" userid="55C0F2E0392A511055C0F2000000004000000120" username="scalitycs" step="REQ_END" status="200" nrobjects="1"

20150216 11:50:13.702 restapi id=0xee97db0 context="generic" cmd="finished" src="94.23.237.168" step="REQ_END" method="GET" uri="/" code="200" elapsed="6ms" input_size="0bytes" output_size="545bytes"

20150216 11:50:13.702 restapi id=0xee97db0 context="generic" cmd="postreadreq" src="94.23.237.168" step="REQ_START" method="DELETE" uri="/hosts"

20150216 11:50:13.702 restapi id=0xee97db0 context="bws" cmd="parseauthz_header" status="ok" login="scalitycs" signature="bWKfrbEET4/DD3ypX1qnRR82K5g="

20150216 11:50:13.702 restapi id=0xee97db0 context="bws" cmd="auth" status="200" user="scalitycs" userid="scalitycs" displayname="Scality Customer Service"

20150216 11:50:13.702 restapi id=0xee97db0 context="bws" src="94.23.237.168" action="BWS_DELETE_OBJECT" bucketid="E212260000000000000000321592594000000220" bucketname="bmor" objid="ACDDA3691EA7426D4ECF85321592594000000320" objname="hosts" userid="55C0F2E0392A511055C0F2000000004000000120" username="scalitycs" step="REQ_START"

20150216 11:50:13.702 restapi id=0xee97db0 context="bws" cmd="content_handler" status="ok"

20150216 11:50:13.702 restapi id=0xee97db0 context="bws" src="94.23.237.168" action="BWS_DELETE_OBJECT" bucketid="E212260000000000000000321592594000000220" bucketname="bmor" objid="ACDDA3691EA7426D4ECF85321592594000000320" objname="hosts" userid="55C0F2E0392A511055C0F2000000004000000120" username="scalitycs" step="REQ_END" status="204"

20150216 11:50:13.702 restapi id=0xee97db0 context="generic" cmd="finished" src="94.23.237.168" step="REQ_END" method="DELETE" uri="/hosts" code="204" elapsed="46ms" input_size="0bytes" output_size="0bytes"

20150216 11:50:13.702 restapi id=0xc4da7c0 context="generic" cmd="postreadreq" src="94.23.237.168" step="REQ_START" method="DELETE" uri="/menu"

20150216 11:50:13.702 restapi id=0xc4da7c0 context="bws" cmd="parseauthz_header" status="ok" login="scalitycs" signature="8TwhPzvkcnXVCgzTgW7/P/cMHLU="

20150216 11:50:13.702 restapi id=0xc4da7c0 context="bws" cmd="auth" status="200" user="scalitycs" userid="scalitycs" displayname="Scality Customer Service"

20150216 11:50:13.702 restapi id=0xc4da7c0 context="bws" src="94.23.237.168" action="BWS_DELETE_BUCKET" bucketid="E212260000000000000000321592594000000220" bucketname="bmor" userid="55C0F2E0392A511055C0F2000000004000000120" username="scalitycs" step="REQ_START"

20150216 11:50:13.702 restapi id=0xc4da7c0 context="bws" cmd="content_handler" status="ok"

20150216 11:50:13.702 restapi id=0xc4da7c0 context="bws" src="94.23.237.168" action="BWS_DELETE_BUCKET" bucketid="E212260000000000000000321592594000000220" bucketname="bmor" userid="55C0F2E0392A511055C0F2000000004000000120" username="scalitycs" step="REQ_END" status="204"

20150216 11:50:13.702 restapi id=0xc4da7c0 context="generic" cmd="finished" src="94.23.237.168" step="REQ_END" method="DELETE" uri="/" code="204" elapsed="59ms" input_size="0bytes" output_size="0bytes"



On Mon, Feb 16, 2015 at 11:49 AM, Benjamin Morge <benjamin.morge@scality.com> wrote:


    ==> authbws-201502160000-0.log <==

    20150216 11:45:12.924 MOD_MSGSTORE_AUTH_BWS authbws_xmlrpc_req: reply user="scalitycs" id="scalitycs" dname="Scality Customer Service" pkey="<hidden>" flags="0" bucketmaxnr="100" bucketmaxsize="-1" reqmaxnr="-1"


    ==> chordbucket-201502160000-0.log <==

    20150216 11:45:12.924 chordbucket id=0x1324ac00 action=GET_BUCKETACL bucketid=E212260000000000000000321592594000000220

    20150216 11:45:12.924 chordbucket id=0x1324ac00 action=GET_BUCKETACL status=SUCCESS

    20150216 11:45:12.924 chordbucket id=0xc4b57d0 action=GET_BUCKETACL bucketid=E212260000000000000000321592594000000220

    20150216 11:45:12.924 chordbucket id=0xc4b57d0 action=GET_BUCKETACL status=SUCCESS

    20150216 11:45:12.924 chordbucket id=0xc420290 action=DEL_BUCKET userid=55C0F2E0392A511055C0F2000000004000000120 bucketid=E212260000000000000000321592594000000220 bucketname=bmor

    20150216 11:45:12.924 chordbucket id=0xc420290 action=DEL_BUCKET status=FAILURE_BUCKETNOTEMPTY

    20150216 11:45:12.924 chordbucket id=0x1328ebd0 action=GET_BUCKETACL bucketid=E212260000000000000000321592594000000220

    20150216 11:45:12.924 chordbucket id=0x1328ebd0 action=GET_BUCKETACL status=SUCCESS

    20150216 11:45:12.924 chordbucket id=0xc46f8f0 action=GET_BUCKETACL bucketid=E212260000000000000000321592594000000220

    20150216 11:45:12.924 chordbucket id=0xc46f8f0 action=GET_BUCKETACL status=SUCCESS

    20150216 11:45:12.924 chordbucket id=0xc424fb0 action=GET_BUCKET bucketid=E212260000000000000000321592594000000220

    20150216 11:45:12.924 chordbucket id=0xc424fb0 action=GET_BUCKET status=SUCCESS


    ==> restapi-201502160000-0.log <==

    20150216 11:45:12.924 restapi id=0xd056c10 context="generic" cmd="postreadreq" src="94.23.237.168" step="REQ_START" method="DELETE" uri="/menu"

    20150216 11:45:12.924 restapi id=0xd056c10 context="bws" cmd="parseauthz_header" status="ok" login="scalitycs" signature="DEkv5eaNTuJpqXMtGgiw6YYiBis="

    20150216 11:45:12.924 restapi id=0xd056c10 context="bws" cmd="auth" status="200" user="scalitycs" userid="scalitycs" displayname="Scality Customer Service"

    20150216 11:45:12.924 restapi id=0xd056c10 context="bws" src="94.23.237.168" action="BWS_DELETE_BUCKET" bucketid="E212260000000000000000321592594000000220" bucketname="bmor" userid="55C0F2E0392A511055C0F2000000004000000120" username="scalitycs" step="REQ_START"

    20150216 11:45:12.924 restapi id=0xd056c10 context="bws" cmd="content_handler" status="ok"

    20150216 11:45:12.924 restapi id=0xd056c10 context="generic" cmd="seterror" msg="BucketNotEmpty" code="409"

    20150216 11:45:12.924 restapi id=0xd056c10 context="bws" src="94.23.237.168" action="BWS_DELETE_BUCKET" bucketid="E212260000000000000000321592594000000220" bucketname="bmor" userid="55C0F2E0392A511055C0F2000000004000000120" username="scalitycs" step="REQ_END" status="409"

    20150216 11:45:12.924 restapi id=0xd056c10 context="generic" cmd="finished" src="94.23.237.168" step="REQ_END" method="DELETE" uri="/" code="409" elapsed="16ms" input_size="0bytes" output_size="133bytes"

    20150216 11:45:12.924 restapi id=0x10a29650 context="generic" cmd="postreadreq" src="94.23.237.168" step="REQ_START" method="GET" uri="/menu"

    20150216 11:45:12.924 restapi id=0x10a29650 context="bws" cmd="parseauthz_header" status="ok" login="scalitycs" signature="9o3mWXMdpy/pu17o9z98yDZSPtU="

    20150216 11:45:12.924 restapi id=0x10a29650 context="bws" cmd="auth" status="200" user="scalitycs" userid="scalitycs" displayname="Scality Customer Service"

    20150216 11:45:12.924 restapi id=0x10a29650 context="bws" src="94.23.237.168" action="BWS_GET_BUCKET" bucketid="E212260000000000000000321592594000000220" bucketname="bmor" userid="55C0F2E0392A511055C0F2000000004000000120" username="scalitycs" step="REQ_START"

    20150216 11:45:12.924 restapi id=0x10a29650 context="bws" cmd="content_handler" status="ok"

    20150216 11:45:12.924 restapi id=0x10a29650 context="bws" cmd="listbucket" name="bmor" prefix="" marker="" next="hosts" max_keys="1000" delimiter="" is_truncated="false"

    20150216 11:45:12.924 restapi id=0x10a29650 context="bws" src="94.23.237.168" action="BWS_GET_BUCKET" bucketid="E212260000000000000000321592594000000220" bucketname="bmor" userid="55C0F2E0392A511055C0F2000000004000000120" username="scalitycs" step="REQ_END" status="200" nrobjects="1"

    20150216 11:45:12.924 restapi id=0x10a29650 context="generic" cmd="finished" src="94.23.237.168" step="REQ_END" method="GET" uri="/" code="200" elapsed="7ms" input_size="0bytes" output_size="545bytes"

    20150216 11:45:12.924 restapi id=0xd056c10 context="generic" cmd="postreadreq" src="94.23.237.168" step="REQ_START" method="POST" uri="/?delete"

    20150216 11:45:12.924 restapi id=0xd056c10 context="bws" cmd="parseauthz_header" status="ok" login="scalitycs" signature="YWK93k58vf5bHSBvPVhWKiPDvNo="

    20150216 11:45:12.924 restapi id=0xd056c10 context="generic" cmd="seterror" msg="SignatureDoesNotMatch" code="403"

    20150216 11:45:12.924 restapi id=0xd056c10 context="bws" cmd="auth" status="403" user="scalitycs" userid="(empty)" displayname="(empty)"

    20150216 11:45:12.924 restapi id=0xd056c10 context="bws" src="94.23.237.168" action="BWS_GET_LISTALLMYBUCKETS" step="REQ_END" status="error" code="403" reason="SignatureDoesNotMatch"

    20150216 11:45:12.924 restapi id=0xd056c10 context="generic" cmd="postreadreq" src="94.23.237.168" step="REQ_ERR" method="POST" uri="/?delete" status="error" code="403" elapsed="0ms"

    20150216 11:45:12.924 restapi id=0xd056c10 context="generic" cmd="finished" src="94.23.237.168" step="REQ_END" method="POST" uri="/?delete" code="403" elapsed="0ms" input_size="0bytes" output_size="110bytes"
```

**Comment by mdomsch** [comment]
0.9.9 wasn't issuing Multi-Object Delete - it was issuing one delete call per object to be deleted.  That's where the Scality server is failing.  I suspect it's not an invalid signature error, so much as Scality does not implement the Multi-Object Delete call, which AWS S3 only added in December 2011.  Please contact Scality support.

I've got a small patch on my github.com/mdomsch/s3cmd bug/no-batch-delete branch which tries to fall back to individual object deletes in this case, which you are welcome to try.

**Comment by dwyart** [comment]
Thanks for the analysis and the patch, I will test it in the coming days.

**Comment by dwyart** [comment]
Hi,

Unfortunately, the patch doesn't work. The attempt to catch the 403 response code doesn't work, because it comes too late: send_request is calling _http_403_handler which exits with sys.exit.

Do you see an alernative way of intercepting the 403 in S3.py ?

I think there was also a typo in the patch: "if cfg.dry_run" should be "if not cfg.dry_run", but as the code is not reached, this is not really important...

Also, Scality plans to implement batch delete in a future version.

Thanks

**Comment by mdomsch** [comment]
Please pull my bug/no-batch-delete again.  I fixed _http_403_handler() to
raise an exception we can catch and fall back via, rather than sys.exit().

The 'if cfg.dry_run()' bit of the previous patch was deleting useless code.


Please report success/failure.

Thanks,
Matt

**Comment by dwyart** [comment]
Concerning dry_run, I was referring to this:
   if cfg.dry_run:
                response = s3.object_delete(S3Uri(item['object_uri_str']))
which was added by your first patch (and is still there).

The modified patch still doesn't work, because send_request tries to return what _http_403_handler has returned, and the part you just modified has a raise, so I think a try/except when calling _http_403_handler would be needed to catch the exception properly and then have s3cmd get the response dict and check for 403 status.

Thanks

**Comment by dwyart** [comment]
I have done a few trials at modifying the code with a try/except, but this is not so straighforward as the exception object stores some data from the response, but we lose the response object. So in s3cmd, checking response["status"] doesn't work. Returning e.status and testing it is == 403 seems to go further, but then I get in an infinite loop where objects are announced as deleted, but no real deletion occurs. This might be related to dry_run (forgot to change it I think), but is still annoying, as the dry_run case might still get into this infinite loop...

I think you will be better than me at this as your are the main developper of s3tools :-)

I also noticed _http_403_handler is not only called in send_request, but also in two other methods, so they might need some modifications also.

**Comment by mdomsch** [comment]
Is there a scality instance publicly reachable that I could try against?
That would make it a lot easier for me.

yes, the 403 handler is called from several places.  Unfortunately, the 403
response from scality in this case doesn't tell us very much (it really
just sends back the 403 it seems), so special-casing for them is hard
without breaking other API-compliant implementations elsewhere.

What's Scality's ETA on supporting the batch delete operation?  It's only
been in the S3 API for 2+ years...

Thanks,
Matt

**Comment by dwyart** [comment]
Batch delete should be available in the coming weeks.

I do not have a public Scality instance at hand, sorry. But I can continue testing your patch if you want (I am still interested in it while waiting for the new feature and for legacy instances that will not be upgraded immediately after the release).

You are right the 403 is not detailed, so not easy to cleanly identify.

If working on the patch is too painful for you, I will try to build on it and make it work even if it is not "perfect".

Thanks

**Comment by mdomsch** [comment]
Yes, please continue as you have time and interest.  I hoped it would be an
easy fix, so I could quickly get it done, but as it's proven more
complicated, I'd love to receive a working sane patch. :-)

Thanks,
Matt

**Comment by rfc1036** [comment]
rb/rm --recursive are not working for me as well. I can provide an account on a Scality system, if it helps.

**Comment by fviard** [comment]
I hope that scality is now fixed for the batch-delete that was not supported.
Please re-open if you are still encountering such issues.
